### ISSUE TITLE
Slash Commands, aren't working for us.

### ISSUE THREAD

**Issue by Myawaa** [diwasatreya/Advanced-Music-Bot#1]
Slash commands aren't working. We've done all the steps you did, on the tutorial, so the bot doesn't register the slash command. It's probably because of the source code. Please fix this issue, I hope we don't get more issues. Ramadan Mubarak. Credits: MASBCS#8131.

**Comment by hisRoyalty** [comment]
@Myawaa please join the server:
discord.gg/dcdev
for further assistance.
If you need anything else, we'll close this :)

**Comment by diwasatreya** [comment]
Fixed Already
