### ISSUE TITLE
new problem

### ISSUE THREAD

**Issue by iShance** [diwasatreya/Advanced-Music-Bot#4]
![image](https://user-images.githubusercontent.com/63490431/193820995-2d8fdda3-410a-446e-8889-f2e4803978ca.png)

**Comment by diwasatreya** [comment]
@Shance90 
Maybe your isp is blocking other dns services. 

Visit Here & follow the steps:
https://www.mongodb.com/community/forums/t/suddenly-unable-to-connect-querytxt-etimeout/117864
