### ISSUE TITLE
NEW 2 ERROR

### ISSUE THREAD

**Issue by iShance** [diwasatreya/Advanced-Music-Bot#5]
**error 1 :** 
![image](https://user-images.githubusercontent.com/63490431/193884144-0015f9f5-5e5c-4e48-bf75-5a4c958ab74c.png)
**error 2 :** 
![image](https://user-images.githubusercontent.com/63490431/193884199-7e63fe78-a363-4481-8402-6a07c98d4df9.png)

**Comment by MICATGAMERS** [comment]
What?

**Comment by diwasatreya** [comment]
@Shance90 
Solution for  first error:
Invite the bot with `application.command` scope
![image](https://user-images.githubusercontent.com/74746579/193954335-a281cb11-b28d-4080-a943-36a16eeacf8f.png)

For second error:
install `canvas@^2.8.0` & make sure you have downloaded font

**Comment by iShance** [comment]
still doesn't work @diwasatreya 
![image](https://user-images.githubusercontent.com/63490431/194052117-5a904a4d-09e0-4307-84e4-5ce910cf0d98.png)

**Comment by diwasatreya** [comment]
> still doesn't work @diwasatreya ![image](https://user-images.githubusercontent.com/63490431/194052117-5a904a4d-09e0-4307-84e4-5ce910cf0d98.png)

What's your canvas & node version?

**Comment by iShance** [comment]
node version : 
![image](https://user-images.githubusercontent.com/63490431/194203962-c58222c0-9855-403d-b35d-9375f1d6a4c5.png)
canvas version : 
![image](https://user-images.githubusercontent.com/63490431/194207907-94fae025-98a4-44db-9246-e0152aca966b.png)

**Comment by diwasatreya** [comment]
@Shance90 remove these two lines from code

https://github.com/diwasatreya/Advanced-Music-Bot/blob/b2a6d4208b6988d49e278c7cb9d7c760a31ccdbf/src/player/events/songAdd.js#L7-L8

**Comment by iShance** [comment]
@diwasatreya thank u !!
